remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: Karthik Subramaniam
description: Karthik Subramaniam's Resume

github:
  pdf_url: https://karthiksubramaniam21.github.io/qe-resume/Karthik_Subramaniam_Resume.pdf
